-- SQLite

CREATE TABLE Product (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	name TEXT NOT NULL,
	code TEXT NOT NULL UNIQUE,
	tags TEXT,
);

CREATE TABLE Recipe (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	name TEXT NOT NULL,
	code TEXT NOT NULL UNIQUE,
	tags TEXT,
);
